### ISSUE TITLE
Latex errors for documents with HTML encoded characters

### ISSUE THREAD

**Issue by Hocdoc** [asciidoctor/asciidoctor-latex#10]
Asciidoctor documents that contain characters that would get encoded in HTML (f.ex. `&` -> `&amp;`) will produce an error when converted to LaTeX and compiled.

Example `test.adoc`:

    Hello & world

Convert it to LaTeX and compile it:

    $ asciidoctor -r asciidoctor-latex/converter.rb -b latex test.adoc
    $ pdflatex test.tex

LaTeX Error:

    ! Misplaced alignment tab character &.
    l.96 Hello &
           amp; world

It would be cool if asciidoctor-latex could replace the HTML () encodings.

Special characters in LaTeX: http://en.wikibooks.org/wiki/LaTeX/Special_Characters

**Comment by jxxcarlson** [comment]
This is now fixed via the texpreprocessor:

https://github.com/asciidoctor/asciidoctor-latex/blob/master/lib/asciidoctor/latex/tex_preprocessor.rb

I am closing this, but please reopen if problems with `asciidoctor-latex` are found.
