### ISSUE TITLE
Use doctest for tests

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-latex#20]
@jirutka, could you add one doctest for latex, one for html?  I could use this as a template for developing a reasonable test suite.  I think this is one of our main priorities.

**Comment by jirutka** [comment]
This backend generates LaTeX, not HTML… isn’t it?

**Comment by mojavelinux** [comment]
It's both. The main focus is LaTeX, but it also has special contexts for
which HTML handlers are provided (e.g., the env block).

**Comment by jirutka** [comment]
@jxxcarlson I’ve prepared it in the branch [doctest](https://github.com/asciidoctor/asciidoctor-latex/commits/doctest). Please note that the current version of DocTest (1.5.1.2) doesn’t support LaTeX yet, so you have to use the [latex](https://github.com/asciidoctor/asciidoctor-doctest/tree/latex) branch.

Run `rake generate:html` to see what the converter actually products. There’s a problem that it renders style and script tags even in the embedded mode with `header_footer` disabled.

**Comment by jxxcarlson** [comment]
It will also generate html - am way from computers now, but will post something on this a bit late. I actually use the html backend more - for http://noteshare.io

**Comment by jxxcarlson** [comment]
Thanks for setting this up!  — having a few problems though:

Am getting errors running `rake generate:html` in the root f my laptop’s 
`asciidoctor-latex` file.

(1) What  I did: 

	- create branch `doctest` of `master` for `asciidoctor-latex` & checkout that branch
	- run `git pull upstream/doctest` 
	- in the parent directory, do  `git clone git@github.com:asciidoctor/asciidoctor-doctest.git1
       - cd into the new directory to do `big pull upstream doctest`

Here is the last log entry for my local `doctest` branch:

  Merge branch 'doctest' of github.com:asciidoctor/asciidoctor-latex into doctest

(2) My errors:

pwd
/Users/carlson/dev/git/asciidoctor-latex
$ rake generate:html
rake aborted!
NameError: uninitialized constant Asciidoctor::DocTest::Latex
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:43:in `block (2 levels) in <top (required)>'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:41:in `new'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:41:in `block in <top (required)>'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:40:in `<top (required)>'
(See full trace by running task with --trace) 

I’m missing something again!! (Aaargh!!)

**Comment by jirutka** [comment]
Have you run `rake install` (or directly `gem build && gem install *.gem`) for asciidoctor-doctest?

> $ rake generate:html

Simple rule of thumb — when there’s a Gemfile in the project (i.e. it uses [Bundler](http://bundler.io) for managing dependencies), always run all ruby commands via `bundle exec`* (e.g. `bundle exec rake generate:html`). Bundler will take care of loading required gems in the correct versions.

_\* Protip: To avoid typing such a long command all over again, create a shell alias for it, e.g. `be`._

> create branch `doctest` of `master` for `asciidoctor-latex` & checkout that branch

btw This step is unnecessary, you can run just `git checkout -b doctest upstream/doctest`.

**Comment by jxxcarlson** [comment]
Still no luck!  — see below.  The line 

	NameError: uninitialized constant Asciidoctor::DocTest::Latex

seems to say that I don’ have the Letex branch despite running

	git pull origin latex

=======================



I reinstalled asciidoctor-doctest like this:

  804  git clone git@github.com:asciidoctor/asciidoctor-doctest.git
  805  cd asciidoctor-doctest/
  806  git br
  807  git remote
  808  git remote -v
  809  git pull origin latex
  810  git br
  811  rake install

then, in  /Users/carlson/dev/git/asciidoctor-latex:

$ rake install
asciidoctor-latex 1.5.0.dev built to pkg/asciidoctor-latex-1.5.0.dev.gem.
asciidoctor-latex (1.5.0.dev) installed.

$ bundle exec rake generate:html
rake aborted!
NameError: uninitialized constant Asciidoctor::DocTest::Latex
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:43:in `block (2 levels) in <top (required)>'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:41:in `new'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:41:in `block in <top (required)>'
/Users/carlson/dev/git/asciidoctor-latex/Rakefile:40:in `<top (required)>'
(See full trace by running task with —trace)

Jim

http://noteshare.io

**Comment by jirutka** [comment]
Sorry, I forgot to mention that you should also run `bundle install` for asciidoctor-latex to update dependencies (it’s kinda routine). I’ve just updated the doctest version in `asciidoctor-latex.gemspec`, just to be sure…

When you run into this kind of problem, run `bundle list` to check what gems do you have on your `$LOAD_PATH`. If `bundle install` doesn’t fix it, then try to remove `Gemfile.lock` and run again.

**Comment by jirutka** [comment]
Keep in mind that you can have installed multiple versions of the same gem. That’s why it doesn’t work as you expects from other systems, Ruby itself doesn’t know which version do you want on the `$LOAD_PATH`. This actually isn’t a common feature among package managers, most of them doesn’t allow multiple versions of the same package — to avoid these issues.

I still don’t understand why Ruby allows this and doesn’t have any mechanism to handle it properly. Bundler is an external tool, not an internal part of Ruby.

**Comment by jxxcarlson** [comment]
Below is the output of `bundle list` for directory `asciidoctor-latex`:  asciidoctor-doctest is listed,
yet it still does not recognize the latex flavor of doctest (I ran bundle install in both places:-{

```
$ bundle list
Gems included by the bundle:
  * activesupport (4.2.0)
  * asciidoctor (1.5.2)
  * asciidoctor-doctest (1.5.1.2)
  * asciidoctor-latex (1.5.0.dev)
  * bundler (1.7.6)
  * colorize (0.7.5)
  * diffy (3.0.7)
  * htmlbeautifier (0.0.12)
  * htmlentities (4.3.3)
  * i18n (0.7.0)
  * json (1.8.1)
  * mini_portile (0.6.0)
  * minitest (5.5.0)
  * minitest-rg (5.1.0)
  * nokogiri (1.6.3.1)
  * rake (10.3.2)
  * thread_safe (0.3.4)
  * tzinfo (1.2.2)
  * yard (0.8.7.6)

```
Jim

http://noteshare.io

**Comment by jirutka** [comment]
There's something wrong in your setup, but I don't know what. :( gemspec specifies asciidoctor-doctest ~> 1.5.2.dev, but there's 1.5.1.2 on your list.

It's too late (4 AM in my TZ), I'll look at it later.

Maybe try to remove all versions of asciidoctor-doctest (gem remove asciidoctor-doctest), install it again (rake install), remove Gemfile.lock in asciidoctor-latex, run bundle install here again.

**Comment by jxxcarlson** [comment]
You spotted it.  I changed

	s.add_development_dependency 'asciidoctor-doctest', '~> 1.5.1,dev’

in asciidoctor-latex.gemspec to

	s.add_development_dependency 'asciidoctor-doctest', '~> 1.5.2.dev’

and reran bundle install; rake install, after which 	

	bundle exec rake generate:html

ran just fine.  I can now see why it is better to reduce/eliminate all the warnings — in this
context they are confusing.

**Comment by mojavelinux** [comment]
>  If bundle install doesn’t fix it, then try to remove Gemfile.lock and run again.

I always recommend deleting Gemfile.lock before running `bundle`, always.

> I still don’t understand why Ruby allows this and doesn’t have any mechanism to handle it properly. Bundler is an external tool, not an internal part of Ruby.

I hate this fact too. This is one of the main reasons I use RVM extensively. It rarely lets me down and seems to keep Bunder behaving.

Take it or leave it, here's what I do. I create a gemset for every project I'm using. I do this by creating two files in the project:

*.ruby-version*

```
2.2
```

*.ruby-gemset*

```
asciidoctor-latex-dev
```

Then, I leave the folder and come back in. RVM sets up a gemset automatically. If I've used the gemset before, I first clean it:

```
$ rvm gemset empty
```

Then I remove `Gemfile.lock`.

Finally, I run Bundler:

```
$ bundle
```

In this case, I had to install the asciidoctor-doctest gem before running Bundler. However, why not link asciidoctor-doctest in the `Gemfile` so it installs it from git?

```
gem 'asciidoctor-doctest', github: 'asciidoctor/asciidoctor-doctest', ref: 'latex'
```

Now I can get the rake task to run.

**Comment by jxxcarlson** [comment]
Got it working — it was an inconsistency in the gem specs that @jirutka spotted
before crashing at 4 am his time.

All these pointers are very helpful!

**Comment by jxxcarlson** [comment]
Doctest up and running … 

- Added the examples/html directory …
- Ran $ bundle exec generate:html
- Ran $ bundle exec rake test  // Hooray!!  It works

doctest rocks!  I will experiment  with it in the next few days.


I don’t see any reason not to merge my local branch ‘dockets’ inot
my local ‘master’  — do you?


=========== messages and errors ====================
One warning with $ bundle exec rake test —verbose


/Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-doctest-1.5.2.dev/lib/asciidoctor/doctest/test.rb:75: warning: instance variable @test_methods not initialized



One error when I ran rake generate:html --

/Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/colorize-0.7.5/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized


Jim

http://noteshare.io

**Comment by mojavelinux** [comment]
:+1:

**Comment by jirutka** [comment]
> it was an inconsistency in the gem specs that @jirutka spotted…

No, that wasn’t the cause of the problem, `~> 1.5.1.dev` actually means `>= 1.5.1, < 1.6.0`, so it includes even `1.5.2.dev`.

The problem is that `bundle install` installs the exact versions specified in Gemfile.lock, if it exists. I had to instructed you to run `bundle update` instead, but I didn’t know about it. :( (shame on me)

> I always recommend deleting Gemfile.lock before running bundle, always.

Not necessary, [bundle update](http://bundler.io/man/bundle-update.1.html) do the same.

> However, why not link asciidoctor-doctest in the Gemfile so it installs it from git?

Thanks for suggestion, it would certainly be better!

> I don’t see any reason not to merge my local branch ‘dockets’ inot my local ‘master’ — do you?

I was not sure if it will work as you expected, therefore I didn’t pushed it to the master branch (yet).

**Comment by jirutka** [comment]
I fixed some bugs in node processors (b35a5b7a78dd12ae90d161f81057e7a9621d3af5, 72e3e1c6de9674517816f23a1f204fb3fbf0618e), removed broken table processing (a193d03cb72127af0fe39cb8aea3e9388c73e9b1) and disabled writing LaTeX boilerplate when running in embedded mode.

When you run `bundle update` and then `bundle exec rake generate:latex`, it should generate latex examples for all the reference examples specified in DocTest, so you can check out what the backend produces.

**Comment by jxxcarlson** [comment]
Wonderful!  

I’ve pulled, merge,and followed your instructions below.  All OK.

The latex examples for the reference examples are generated.
This gives a very useful to-do list.

A couple of questions.

  - Is there a way of running the tests for just one backend (html or tex)?

  - Is there a way of running just one test?  This would be useful when working
on a specific item.

**Comment by jirutka** [comment]
> The latex examples for the reference examples are generated.

Actually not all of them, many are empty or incomplete, because the latex backend doesn’t support all nodes yet.

>  - Is there a way of running the tests for just one backend (html or tex)?

Yeah, you can see it [here](https://github.com/asciidoctor/asciidoctor-latex/blob/doctest/Rakefile#L22-L38) or in the tasks description when you run `bundle exec rake -D`.

> Is there a way of running just one test?

Yes, see https://github.com/asciidoctor/asciidoctor-doctest/issues/5#issuecomment-68411715.

**Comment by jxxcarlson** [comment]
Should we close this issue?  I now have doctest up and running, so the goal now is to increase test coverage and ultimately to have full coverage.

**Comment by jxxcarlson** [comment]
Am now using doctest to test the html backend.  (Yay!)

My priority is to get the html backend well-tested & then released.  I am using it in http://noteshare.io and am pretty happy with it. If we could release this and get it incorporated in @mogzzter's Asciidoc Live Preview, Atom, and Brackets, that would be great (for mathematicians, physicists, chemists, etc.)
