### ISSUE TITLE
Percent sign % is not escaped in output latex

### ISSUE THREAD

**Issue by giuliano52** [asciidoctor/asciidoctor-latex#25]
The following adoc trigger the problem:
```
== Percent sign is not escaped

[quote]
House prices will rise by 30% in five years
```
In the produced latex file the % is not escaped and it will generate an error.

If we in the latex file the '%' is substituted manualy with '\%' everything works fine. Thank you

**Comment by jxxcarlson** [comment]
Thanks for catching this.  I fixed this in the latest version.  Please let me know if there is a problem with it -- and keep the bug reports coming.  They help me to get to a full implementation faster.  BTW, you need to use xelatex the way things are configured now.

**Comment by giuliano52** [comment]
Great. Thank you
