### ISSUE TITLE
Add style sheet?

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-latex#30]
Is there a way to package a CSS style sheet with the distribution of Asciidoctor-latex?  This would be a small file that would be loaded after the main Asciidoctor CSS file.

**Comment by jxxcarlson** [comment]
I suppose one could put foo.css in the data directory.  But how would asciidoctor-latex know it is there?

**Comment by mojavelinux** [comment]
Yes, I recommend putting stylesheets in the data directory. That's how Asciidoctor core does it. You can see how Asciidoctore core locates this file by looking at the following lines of code:

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L176
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L182
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/stylesheets.rb#L11

Essentially, you use the main source file in the gem to get the path of the gem. From there, you build the path to the data directory. (There is a built-in way in RubyGems to get the path to the data directory for a gem, but it's questionable whether it's a public API).

I may have mentioned this already, but you can now use a DocinfoProcessor to contribute additional content to the `<head>` of the HTML document. For an example, see https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/license-url-docinfoprocessor.rb (that's the shorthand version of an extension...you can also see the longhand here https://github.com/asciidoctor/asciidoctor/blob/master/test/extensions_test.rb#L120).

**Comment by jxxcarlson** [comment]
Done

**Comment by mojavelinux** [comment]
:+1:
