### ISSUE TITLE
Monospace with \texttt instead of \tt

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor-latex#36]
I'm having a problem with `monospace`. I'm not a latex expect, but when I try to compile a document with monospace I end up with an error.

Let's see how it is implemented:

```bash
$ echo "\`monospace\` _italic_ *bold*" | asciidoctor-latex -a header=no -
```

The result was:

```latex
{\tt monospace} \emph{italic} \textbf{bold}
```

I propose to change `{\tt monospace}` to ` \texttt{monospace}` (works for me).

The `\texttt` is documented at https://en.wikibooks.org/wiki/LaTeX/Fonts

**Comment by jxxcarlson** [comment]
Thanks!  Will be able to look at it in about an hour.  Keep those bug reports coming!!

**Comment by jxxcarlson** [comment]
Hi there!

I think that your difficulty has to do with the backlashes, not
with \tt or \textt per se.  The following works:

`monospace` _italic_ *bold* => {\tt monospace} \emph{italic} \textbf{bold}

but this (for example)

`\monospace` _italic_ *bold* =>{\tt \monospace} \emph{italic} \textbf{bold}

won’t work because for TeX, backslash has a special meaning.  That is
why you are getting errors.


If you have things
like \foo \bar in your source text, then you can do something like this:

----
\monospace is a macro
----

Use four dashes above and below.  This will be translated into valid tex.
Here we are using what is called a `verbatim` macro package for TeX.
Asciidoctor-LaTeX knows how to translate the above into valid TeX.

If you need it in-line, I will need to do a little work to add this feature.

Best regards,

Jim


http://noteshare.io <http://noteshare.io/>
http://home.noteshareblog.io <http://home.noteshareblog.io/>

**Comment by edusantana** [comment]
No, I put the backlash in the `echo` command because if I leave the ` it will be interpreted as a bash command:

```bash
$ echo "`monospace`"
monospace: command not found
```

**Comment by jxxcarlson** [comment]
OK, I agree that this works as stated - no errors. What is it that is giving you errors?

When I run {\tt whatever} and compare it to \texttt{whatever}, the outputs look the same to me.

**Comment by edusantana** [comment]
```
$ cat rascunho.adoc
== my Chapter

`monospace`

$ cat rascunho.adoc | asciidoctor-latex -b latex -d book -a header=no -a numbered -
\hypertarget{_my_chapter}{\chapter{my Chapter}}
{\tt monospace}
```

So I copy this text, and put inside an template with this packages:


```latex
\usepackage{lmodern}			% Usa a fonte Latin Modern
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}		% Codificacao do documento (conversão automática dos acentos)
\usepackage{lastpage}			% Usado pela Ficha catalográfica
\usepackage{indentfirst}		% Indenta o primeiro parágrafo de cada seção.
\usepackage{color}				% Controle das cores
\usepackage{graphicx}			% Inclusão de gráficos
\usepackage{microtype} 			% para melhorias de justificação
```

When I compile it with pdflatex:

    ! Class memoir Error: Font command \tt is not supported.

I see now that asciidoc-latex was made to work with xelatex:

```
$ asciidoctor-latex -b latex rascunho.adoc 
$ pdflatex rascunho.tex 
(....)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

$ xelatex rascunho.tex 
(...)
Output written on rascunho.pdf (1 page).
```

Since I was using with header=no, the produced code was made for `xelatex', not working with `pdflatex`.

> I think that the {\tt} command is not inside of these packages.

When I change to use with `texttt` my tex compiles with pdflatex,

**Comment by edusantana** [comment]
Here's the complete file:
https://gist.github.com/edusantana/341c947dcffa9da4c27d

The error:
```
! Class memoir Error: Font command \tt is not supported.

See the memoir class documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.445 Testing {\tt
                   monospace}.
? 
! Emergency stop.
 ...                                              
                                                  
l.445 Testing {\tt
                   monospace}.
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on document.log.
```

> When I change the \tt to \texttt it works.

**Comment by edusantana** [comment]
The microfile that you wrote with the class article ( at #37 ) , worked. It compiled with tt and texttt, both became monospace. I will test with `memoir` class.

**Comment by edusantana** [comment]
Yes, the problem is with the `memoir` class:

```latex
\documentclass[11pt, oneside]{memoir} 
\begin{document}

{\tt monospace with tt}

\texttt{monospace with texttt}
\end{document}

```

This one doesn't compile.

**Comment by edusantana** [comment]
I have tested how [pandoc](http://pandoc.org/getting-started.html) does it, it uses `\texttt`:

```
$ cat pandoc.md 
`monospace with pandoc` *italic* **bold**
$ pandoc pandoc.md -t latex
\texttt{monospace with pandoc} \emph{italic} \textbf{bold}
```

**Comment by jxxcarlson** [comment]
Thanks, I’ll change to \textt later today

**Comment by jxxcarlson** [comment]
I’ve  changed to \textt — could you
test?  I am having some system
problems and can’t be sure that all is OK
until I get them fixed.

**Comment by edusantana** [comment]
```bash
$ echo "\`monospace\` _italic_ *bold*" | asciidoctor-latex -a header=no -
```

the output was:

```latex
\textt{ monospace} \emph{italic} \textbf{bold}
```

I think there's an extra space: `textt{ monospace}` it should be -> `textt{monospace}`

**Comment by jxxcarlson** [comment]
Should be ok now -- no extra space.  Again, could you double check?

Thanks so much for bringing up this problem -- sorry it took so much back and forth.
Please let me know if there are further problems .. the converter is still beta software

**Comment by edusantana** [comment]
It's okay now. thanks!
May I suggest [put the number of the issue in the commit message](https://help.github.com/articles/closing-issues-via-commit-messages/)? This way when can track it more easy...

**Comment by johnyf** [comment]
For those led here by searching about the `memoir` package error regarding `\tt` (mentioned [above](https://github.com/asciidoctor/asciidoctor-latex/issues/36#issuecomment-115272532)), the `memoir` class does not define old font commands (LaTeX 2.09) by default. These commands can be activated by explicitly passing the class option `oldfontcommands` to `memoir`, as described in [this answer](https://tex.stackexchange.com/a/129283/8666).
