### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-latex#5]
So far all my testing has been informal and file-and-eyeball-based: run a file through the converter and see if the output does what it should.  If one knew enough to operate with nodes and strings, there could be a better solution: build a node, apply a method to it, examine the result.  Any thoughts on this? If I had an example or two I could probably figure out what to do.  Rspec works for me.

**Comment by jxxcarlson** [comment]
Am now using @jirutka 's excellent https://github.com/asciidoctor/asciidoctor-doctest

**Comment by mojavelinux** [comment]
:beers:

**Comment by jirutka** [comment]
I don’t see any (valid) testing examples [here](https://github.com/asciidoctor/asciidoctor-latex/tree/master/test/examples/tex), so it’s currently not used. :( I’ve done just the setup part, but I don’t know what it _should_ render, so I can’t generate _and_ verify the testing examples.

**Comment by jxxcarlson** [comment]
I'll try to get on this as soon as possible.
